MODULE UTILS
  USE, INTRINSIC :: ISO_FORTRAN_ENV
  IMPLICIT NONE

CONTAINS

ELEMENTAL LOGICAL FUNCTION ISA(c)
  CHARACTER, INTENT(in) :: c

  isa = ('a'.LE.c .AND. c.LE.'z') .OR. ('A'.LE.c .AND. c.LE.'Z')
END FUNCTION ISA

ELEMENTAL LOGICAL FUNCTION ISN(c)
  CHARACTER, INTENT(in) :: c

  isn = '0'.LE.c .AND. c.LE.'9'
END FUNCTION ISN

ELEMENTAL LOGICAL FUNCTION ISW(c)
  CHARACTER, INTENT(in) :: c

  isw = c.EQ.CHAR(9) .OR. c.EQ.' '
END FUNCTION ISW

INTEGER FUNCTION NLINES(f)
  CHARACTER*(*) f
  CHARACTER c
  INTEGER ios

  OPEN(UNIT=99, FILE=f, STATUS='old')

  nlines=0
  DO
     READ(99, '(A)', IOSTAT=ios) c
     IF (ios.EQ.IOSTAT_END) EXIT
     nlines = nlines + 1
  END DO

  CLOSE(99)
END FUNCTION NLINES

END MODULE UTILS
